name: Azure Login Test

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Azure Subscription
        run: az account show
